version: "3.9"

services:
  web:
    image: tecobit-learning-platform:latest
    build: .
    command: /entrypoint.sh
    env_file:
      - .env.production
    volumes:
      - static_volume:/app/staticfiles
    restart: always
volumes:
  static_volume: